### ISSUE TITLE
Can't filter on strings containing right parenthesis - e.g.  "number": "(123) 456-7890"

### ISSUE THREAD

**Issue by orewarokubanda** [PopeFelix/p5-json-path#33]
From the fine documentation - "Filters are specified using the '?(' token, terminated by ')'. Anything in between these two tokens is treated as a filter expression." 

As implemented elsewhere, parentheses in filter strings within square brackets and quotes are fine. Unfortunately, the perl version hard truncates the filter expression at its initial right parenthesis, rather than the concluding token right parenthesis, producing the following error:

Uncaught exception from user code:
        Error in filter: Can't find string terminator '"' anywhere before EOF at (eval 18) line 1.
         at /opt/perl522/lib/site_perl/5.22.0/JSON/Path.pm line 107.
        JSON::Path::Evaluator::_process_perl(JSON::Path::Evaluator=HASH(0x231f2d0), ARRAY(0x2845f98), "\$_->{number} eq \"(123") called at /opt/perl522/lib/site_perl/5.22.0/JSON/Path/Evaluator.pm line 239

Currently the only workaround is to massage ')' characters out of the base JSON via deletion or substitution and then filter on the massaged data. Less than optimal.

Can you please look in to fixing this? Or alternatively, maybe suggest a way to tweak the query so as to work with the as-is code base? 

Thanks so much for your time and efforts!

```

#!/usr/local/bin/perl

  use strict;
  use JSON::Path;
  local $JSON::Path::Safe = 0;
  use diagnostics;

  my $json   = '{ "phones": [ { "type" : "iPhone", "number": "(123rpar 456-7890" }, { "type" : "home", "number": "(123) 456-7890" } ] }';

  my $phone_number;
  $phone_number = '(123) 456-7890';  
  $phone_number = '(123rpar 456-7890'; # <-- works, the above does not

  my $jpath   = JSON::Path->new( '$.phones.[?($_->{number} eq "' . "$phone_number" . '")].type');
  my @types = $jpath->values($json);
  print("Phone type is: $types[0]\n");
```

**Comment by PopeFelix** [comment]
OK, I see where this is happening, but figuring out how to fix it is going to take a bit.

**Comment by PopeFelix** [comment]
Well, not so long as all that, apparently. I have a fix in place; just need to add a test for it.

**Comment by PopeFelix** [comment]
This will be fixed in the next release

**Comment by orewarokubanda** [comment]
Thanks so much for your time and effort! Will I get a heads up when the release drops? Or, do you have a rough idea when I should start checking for it? Thanks again.
