### ISSUE TITLE
Eliminate the dependence on JSON::Parse

### ISSUE THREAD

**Issue by bschmalhofer** [PopeFelix/p5-json-path#42]
I was wondering why JSON::Parse is required and found that it is used only in a single test script. I propose to use JSON::MaybeXS in _t/evaluator/path-construction-fail.t_. With that change the dependency can be eliminated.

**Comment by PopeFelix** [comment]
I don't remember why I introduced the dependency on JSON::Parse, so as long as the tests pass I'm happy to do away with it.

**Comment by PopeFelix** [comment]
Dependency on JSON::Parse has been eliminated
